"""Generates tools/bridge/src/com/rustcraft/coremod/LiveWriterPlan.java from the
committed pre-hook live-shadow profile. Fail-closed: refuses unless every required
hook is QUALIFIED and the manifest hash matches. The plan is the single source of
truth for which hook sites the transformers may instrument."""
import hashlib
import json
import pathlib

ROOT = pathlib.Path(r"D:/minecraftrust")
PROFILE = ROOT / "tools/live-capture/live-shadow-profile.json"
MANIFEST = ROOT / "tools/live-capture/required-live-writer-hooks.json"
OUT = ROOT / "tools/bridge/src/com/rustcraft/coremod/LiveWriterPlan.java"

profile = json.loads(PROFILE.read_text(encoding="utf-8"))
manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
manifest_sha = hashlib.sha256(MANIFEST.read_bytes()).hexdigest()

if not profile.get("all_required_qualified"):
    raise SystemExit("REFUSED: profile is not fully qualified")
if profile.get("required_hooks_manifest_sha256") != manifest_sha:
    raise SystemExit("REFUSED: profile was built from a different manifest revision")
for hook in profile["required_hooks"]:
    if hook["status"] != "QUALIFIED":
        raise SystemExit("REFUSED: hook %s is %s" % (hook["id"], hook["status"]))

OWNER = {"net.minecraft.world.World", "net.minecraft.world.chunk.Chunk",
         "net.minecraft.world.chunk.storage.ExtendedBlockStorage",
         "net.minecraft.world.chunk.BlockStateContainer",
         "net.minecraft.world.chunk.NibbleArray", "net.minecraft.util.BitArray"}
PACKET = {"net.minecraft.network.play.server.SPacketChunkData"}


def transformer_for(hook):
    cls = hook["class"]
    if cls in PACKET:
        return "PACKET"
    if cls in OWNER:
        return "OWNERSHIP"
    return "PUBLICATION"


def jstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


plan_entries = []
hooks = manifest["required_hooks"]
status_by_id = {h["id"]: h["status"] for h in profile["required_hooks"]}
hash_by_class = profile["expected_class_hashes"]
for hook in hooks:
    cls = hook["class"]
    fp = hook["fingerprint"]
    if fp["kind"] == "BCI_ASSERTIONS":
        fingerprint_expr = "new String[][]{%s}" % ", ".join(
            "{%s, %s}" % (jstr(str(a["bci"])), jstr(a["expect"])) for a in fp["assertions"])
    else:
        fingerprint_expr = "EMPTY_FINGERPRINT"
    plan_entries.append(
        "new Hook(%s, %s, %s, %s, %s, %s, %s, %s, %s)" % (
            jstr(hook["id"]), jstr(transformer_for(hook)), jstr(cls), jstr(hook["method"]),
            jstr(hook["descriptor"]), jstr(hook["hook_type"]),
            jstr("liveWriter." + hook["id"] + "." + cls.rsplit(".", 1)[-1] + "." + hook["method"].replace("<init>", "ctor")),
            fingerprint_expr,
            jstr(hash_by_class[cls])))

java = f"""package com.rustcraft.coremod;

/**
 * GENERATED by tools/live-capture/generate_live_writer_plan.py from the committed
 * pre-hook profile tools/live-capture/live-shadow-profile.json
 * (manifest tools/live-capture/required-live-writer-hooks.json @ {manifest_sha[:16]}…).
 * Do not edit by hand. Every entry is an already-QUALIFIED descriptor; the
 * transformers refuse to instrument anything that is not in this plan, and each
 * entry carries the pre-hook class hash that the source bytes must match.
 *
 * Profile identity bound at generation: minecraft_server {profile["qualification"]["minecraft_server_jar_sha256"][:16]}…,
 * forge build {profile["forge_build"]}, profile {profile["qualification"]["profile"]}.
 */
public final class LiveWriterPlan {{
    public static final String[][] EMPTY_FINGERPRINT = new String[0][];

    public static final class Hook {{
        public final String id;
        public final String transformer;   // OWNERSHIP | PUBLICATION | PACKET
        public final String className;     // fully-qualified transformed name
        public final String methodName;    // SRG/runtime name; <init> for constructors
        public final String descriptor;    // exact JVM descriptor
        public final String hookType;      // WRITE_BEGIN | PRIVATE_BUILD_BEGIN | ...
        public final String operationId;   // unique injected marker + duplicate-detection anchor
        public final String[][] fingerprint; // {{bci, expected instruction fragment}} or empty
        public final String preHookClassSha256;

        Hook(String id, String transformer, String className, String methodName, String descriptor,
             String hookType, String operationId, String[][] fingerprint, String preHookClassSha256) {{
            this.id = id;
            this.transformer = transformer;
            this.className = className;
            this.methodName = methodName;
            this.descriptor = descriptor;
            this.hookType = hookType;
            this.operationId = operationId;
            this.fingerprint = fingerprint;
            this.preHookClassSha256 = preHookClassSha256;
        }}

        public boolean hasFingerprint() {{
            return fingerprint != EMPTY_FINGERPRINT && fingerprint.length > 0;
        }}
    }}

    /** Negative-control factory: same hook with a wrong pre-hook class hash. */
    public static Hook doctoredSha(Hook hook, String sha) {{
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, hook.descriptor,
                hook.hookType, hook.operationId, hook.fingerprint, sha);
    }}

    /** Negative-control factory: same hook with an altered descriptor. */
    public static Hook doctoredDescriptor(Hook hook, String descriptor) {{
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, descriptor,
                hook.hookType, hook.operationId, hook.fingerprint, hook.preHookClassSha256);
    }}

    /** Negative-control factory: same hook with shifted/missing/duplicated anchors. */
    public static Hook doctoredFingerprint(Hook hook, String[][] fingerprint) {{
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, hook.descriptor,
                hook.hookType, hook.operationId, fingerprint, hook.preHookClassSha256);
    }}

    /** Profile identity binding: any change here requires regeneration + requalification. */
    public static final String FORGE_BUILD = {jstr(profile["forge_build"])};
    public static final String QUALIFICATION_PROFILE = {jstr(profile["qualification"]["profile"])};
    public static final String REQUIRED_HOOKS_MANIFEST_SHA256 = {jstr(manifest_sha)};

    public static final Hook[] HOOKS = {{
        {",\n        ".join(plan_entries)}
    }};

    private LiveWriterPlan() {{ }}
}}
"""
OUT.write_text(java, encoding="utf-8", newline="")
print("generated", OUT, "hooks:", len(plan_entries))
