[package]
name = "nbt-region-experiment"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
nbt = { path = "../../crates/nbt" }
fastnbt = "=2.6.3"
simdnbt = "=0.10.0"
flate2 = { version = "=1.1.10", default-features = false, features = ["zlib-rs"] }
zlib-rs = "=0.6.8"
serde_json = "=1.0.145"

[profile.release]
debug = true
