"""JVM opcode tables for Java 8 (class file major version <= 52) bytecode.

Operand kinds understood by the instruction walker in classfile.py:

    ""            no operands
    "b"           one signed byte
    "s"           one signed short
    "cp1"         one-byte constant-pool index (ldc)
    "cp2"         two-byte constant-pool index
    "local"       one-byte local-variable index
    "iinc"        local index + signed byte increment
    "br2"/"br4"   branch offset relative to instruction start
    "newarray"    primitive array type byte
    "tableswitch"/"lookupswitch"/"wide"  decoded specially
"""

# opcode -> (mnemonic, operand kind, semantic kind)
# semantic kind drives what the indexer extracts:
#   invoke / field / type / num / string / branch / plain
OPCODES = {
    0x00: ("nop", "", "plain"),
    0x01: ("aconst_null", "", "plain"),
    0x02: ("iconst_m1", "", "num"),
    0x03: ("iconst_0", "", "num"),
    0x04: ("iconst_1", "", "num"),
    0x05: ("iconst_2", "", "num"),
    0x06: ("iconst_3", "", "num"),
    0x07: ("iconst_4", "", "num"),
    0x08: ("iconst_5", "", "num"),
    0x09: ("lconst_0", "", "num"),
    0x0A: ("lconst_1", "", "num"),
    0x0B: ("fconst_0", "", "num"),
    0x0C: ("fconst_1", "", "num"),
    0x0D: ("fconst_2", "", "num"),
    0x0E: ("dconst_0", "", "num"),
    0x0F: ("dconst_1", "", "num"),
    0x10: ("bipush", "b", "num"),
    0x11: ("sipush", "s", "num"),
    0x12: ("ldc", "cp1", "ldc"),
    0x13: ("ldc_w", "cp2", "ldc"),
    0x14: ("ldc2_w", "cp2", "ldc2"),
    0x15: ("iload", "local", "plain"),
    0x16: ("lload", "local", "plain"),
    0x17: ("fload", "local", "plain"),
    0x18: ("dload", "local", "plain"),
    0x19: ("aload", "local", "plain"),
    0x1A: ("iload_0", "", "plain"),
    0x1B: ("iload_1", "", "plain"),
    0x1C: ("iload_2", "", "plain"),
    0x1D: ("iload_3", "", "plain"),
    0x1E: ("lload_0", "", "plain"),
    0x1F: ("lload_1", "", "plain"),
    0x20: ("lload_2", "", "plain"),
    0x21: ("lload_3", "", "plain"),
    0x22: ("fload_0", "", "plain"),
    0x23: ("fload_1", "", "plain"),
    0x24: ("fload_2", "", "plain"),
    0x25: ("fload_3", "", "plain"),
    0x26: ("dload_0", "", "plain"),
    0x27: ("dload_1", "", "plain"),
    0x28: ("dload_2", "", "plain"),
    0x29: ("dload_3", "", "plain"),
    0x2A: ("aload_0", "", "plain"),
    0x2B: ("aload_1", "", "plain"),
    0x2C: ("aload_2", "", "plain"),
    0x2D: ("aload_3", "", "plain"),
    0x2E: ("iaload", "", "plain"),
    0x2F: ("laload", "", "plain"),
    0x30: ("faload", "", "plain"),
    0x31: ("daload", "", "plain"),
    0x32: ("aaload", "", "plain"),
    0x33: ("baload", "", "plain"),
    0x34: ("caload", "", "plain"),
    0x35: ("saload", "", "plain"),
    0x36: ("istore", "local", "plain"),
    0x37: ("lstore", "local", "plain"),
    0x38: ("fstore", "local", "plain"),
    0x39: ("dstore", "local", "plain"),
    0x3A: ("astore", "local", "plain"),
    0x3B: ("istore_0", "", "plain"),
    0x3C: ("istore_1", "", "plain"),
    0x3D: ("istore_2", "", "plain"),
    0x3E: ("istore_3", "", "plain"),
    0x3F: ("lstore_0", "", "plain"),
    0x40: ("lstore_1", "", "plain"),
    0x41: ("lstore_2", "", "plain"),
    0x42: ("lstore_3", "", "plain"),
    0x43: ("fstore_0", "", "plain"),
    0x44: ("fstore_1", "", "plain"),
    0x45: ("fstore_2", "", "plain"),
    0x46: ("fstore_3", "", "plain"),
    0x47: ("dstore_0", "", "plain"),
    0x48: ("dstore_1", "", "plain"),
    0x49: ("dstore_2", "", "plain"),
    0x4A: ("dstore_3", "", "plain"),
    0x4B: ("astore_0", "", "plain"),
    0x4C: ("astore_1", "", "plain"),
    0x4D: ("astore_2", "", "plain"),
    0x4E: ("astore_3", "", "plain"),
    0x4F: ("iastore", "", "plain"),
    0x50: ("lastore", "", "plain"),
    0x51: ("fastore", "", "plain"),
    0x52: ("dastore", "", "plain"),
    0x53: ("aastore", "", "plain"),
    0x54: ("bastore", "", "plain"),
    0x55: ("castore", "", "plain"),
    0x56: ("sastore", "", "plain"),
    0x57: ("pop", "", "plain"),
    0x58: ("pop2", "", "plain"),
    0x59: ("dup", "", "plain"),
    0x5A: ("dup_x1", "", "plain"),
    0x5B: ("dup_x2", "", "plain"),
    0x5C: ("dup2", "", "plain"),
    0x5D: ("dup2_x1", "", "plain"),
    0x5E: ("dup2_x2", "", "plain"),
    0x5F: ("swap", "", "plain"),
    0x60: ("iadd", "", "plain"),
    0x61: ("ladd", "", "plain"),
    0x62: ("fadd", "", "plain"),
    0x63: ("dadd", "", "plain"),
    0x64: ("isub", "", "plain"),
    0x65: ("lsub", "", "plain"),
    0x66: ("fsub", "", "plain"),
    0x67: ("dsub", "", "plain"),
    0x68: ("imul", "", "plain"),
    0x69: ("lmul", "", "plain"),
    0x6A: ("fmul", "", "plain"),
    0x6B: ("dmul", "", "plain"),
    0x6C: ("idiv", "", "plain"),
    0x6D: ("ldiv", "", "plain"),
    0x6E: ("fdiv", "", "plain"),
    0x6F: ("ddiv", "", "plain"),
    0x70: ("irem", "", "plain"),
    0x71: ("lrem", "", "plain"),
    0x72: ("frem", "", "plain"),
    0x73: ("drem", "", "plain"),
    0x74: ("ineg", "", "plain"),
    0x75: ("lneg", "", "plain"),
    0x76: ("fneg", "", "plain"),
    0x77: ("dneg", "", "plain"),
    0x78: ("ishl", "", "plain"),
    0x79: ("lshl", "", "plain"),
    0x7A: ("ishr", "", "plain"),
    0x7B: ("lshr", "", "plain"),
    0x7C: ("iushr", "", "plain"),
    0x7D: ("lushr", "", "plain"),
    0x7E: ("iand", "", "plain"),
    0x7F: ("land", "", "plain"),
    0x80: ("ior", "", "plain"),
    0x81: ("lor", "", "plain"),
    0x82: ("ixor", "", "plain"),
    0x83: ("lxor", "", "plain"),
    0x84: ("iinc", "iinc", "plain"),
    0x85: ("i2l", "", "plain"),
    0x86: ("i2f", "", "plain"),
    0x87: ("i2d", "", "plain"),
    0x88: ("l2i", "", "plain"),
    0x89: ("l2f", "", "plain"),
    0x8A: ("l2d", "", "plain"),
    0x8B: ("f2i", "", "plain"),
    0x8C: ("f2l", "", "plain"),
    0x8D: ("f2d", "", "plain"),
    0x8E: ("d2i", "", "plain"),
    0x8F: ("d2l", "", "plain"),
    0x90: ("d2f", "", "plain"),
    0x91: ("i2b", "", "plain"),
    0x92: ("i2c", "", "plain"),
    0x93: ("i2s", "", "plain"),
    0x94: ("lcmp", "", "plain"),
    0x95: ("fcmpl", "", "plain"),
    0x96: ("fcmpg", "", "plain"),
    0x97: ("dcmpl", "", "plain"),
    0x98: ("dcmpg", "", "plain"),
    0x99: ("ifeq", "br2", "branch"),
    0x9A: ("ifne", "br2", "branch"),
    0x9B: ("iflt", "br2", "branch"),
    0x9C: ("ifge", "br2", "branch"),
    0x9D: ("ifgt", "br2", "branch"),
    0x9E: ("ifle", "br2", "branch"),
    0x9F: ("if_icmpeq", "br2", "branch"),
    0xA0: ("if_icmpne", "br2", "branch"),
    0xA1: ("if_icmplt", "br2", "branch"),
    0xA2: ("if_icmpge", "br2", "branch"),
    0xA3: ("if_icmpgt", "br2", "branch"),
    0xA4: ("if_icmple", "br2", "branch"),
    0xA5: ("if_acmpeq", "br2", "branch"),
    0xA6: ("if_acmpne", "br2", "branch"),
    0xA7: ("goto", "br2", "branch"),
    0xA8: ("jsr", "br2", "branch"),
    0xA9: ("ret", "local", "plain"),
    0xAA: ("tableswitch", "tableswitch", "branch"),
    0xAB: ("lookupswitch", "lookupswitch", "branch"),
    0xAC: ("ireturn", "", "plain"),
    0xAD: ("lreturn", "", "plain"),
    0xAE: ("freturn", "", "plain"),
    0xAF: ("dreturn", "", "plain"),
    0xB0: ("areturn", "", "plain"),
    0xB1: ("return", "", "plain"),
    0xB2: ("getstatic", "cp2", "field"),
    0xB3: ("putstatic", "cp2", "field"),
    0xB4: ("getfield", "cp2", "field"),
    0xB5: ("putfield", "cp2", "field"),
    0xB6: ("invokevirtual", "cp2", "invoke"),
    0xB7: ("invokespecial", "cp2", "invoke"),
    0xB8: ("invokestatic", "cp2", "invoke"),
    0xB9: ("invokeinterface", "invokeinterface", "invoke"),
    0xBA: ("invokedynamic", "invokedynamic", "invokedynamic"),
    0xBB: ("new", "cp2", "type"),
    0xBC: ("newarray", "newarray", "plain"),
    0xBD: ("anewarray", "cp2", "type"),
    0xBE: ("arraylength", "", "plain"),
    0xBF: ("athrow", "", "plain"),
    0xC0: ("checkcast", "cp2", "type"),
    0xC1: ("instanceof", "cp2", "type"),
    0xC2: ("monitorenter", "", "plain"),
    0xC3: ("monitorexit", "", "plain"),
    0xC4: ("wide", "wide", "special"),
    0xC5: ("multianewarray", "multianewarray", "type"),
    0xC6: ("ifnull", "br2", "branch"),
    0xC7: ("ifnonnull", "br2", "branch"),
    0xC8: ("goto_w", "br4", "branch"),
    0xC9: ("jsr_w", "br4", "branch"),
}

NEWARRAY_TYPES = {
    4: "boolean", 5: "char", 6: "float", 7: "double",
    8: "byte", 9: "short", 10: "int", 11: "long",
}

CONSTANT_Utf8 = 1
CONSTANT_Integer = 3
CONSTANT_Float = 4
CONSTANT_Long = 5
CONSTANT_Double = 6
CONSTANT_Class = 7
CONSTANT_String = 8
CONSTANT_Fieldref = 9
CONSTANT_Methodref = 10
CONSTANT_InterfaceMethodref = 11
CONSTANT_NameAndType = 12
CONSTANT_MethodHandle = 15
CONSTANT_MethodType = 16
CONSTANT_Dynamic = 17
CONSTANT_InvokeDynamic = 18
CONSTANT_Module = 19
CONSTANT_Package = 20
