#!/usr/bin/env python3
"""
Comprehensive Twin-World Generated-Chunk Semantic Parity Analyzer.
Distinguishes base terrain (stone, water, bedrock, dirt generated by setBlocksInChunk/primer)
from decoration / random ticking passes (leaves, plants, entities).
"""
import io, os, sys, glob, zlib, struct
from collections import Counter
from compare_worlds import load_region_chunks, extract_chunk_block_state

def analyze_all_chunks(dir_j, dir_r):
    regions_j = glob.glob(os.path.join(dir_j, "region", "r.*.*.mca"))
    regions_r = glob.glob(os.path.join(dir_r, "region", "r.*.*.mca"))
    reg_names = sorted(set(os.path.basename(p) for p in regions_j).intersection(os.path.basename(p) for p in regions_r))
    
    total_chunks = 0
    identical_chunks_exact = 0
    identical_chunks_blocks = 0
    mismatched_blocks_total = 0
    
    # Track which block IDs mismatched
    mismatched_block_ids = Counter()
    
    # Track base terrain mismatches (Y < 4, i.e. underground / sea level where setBlocksInChunk dominates)
    base_terrain_sections_compared = 0
    base_terrain_sections_identical = 0
    base_terrain_blocks_mismatched = 0
    
    # Surface/decoration sections (Y >= 4)
    surface_sections_compared = 0
    surface_sections_identical = 0
    
    for rname in reg_names:
        pj = os.path.join(dir_j, "region", rname)
        pr = os.path.join(dir_r, "region", rname)
        cj = load_region_chunks(pj)
        cr = load_region_chunks(pr)
        common_coords = sorted(set(cj.keys()).intersection(cr.keys()))
        
        for coord in common_coords:
            total_chunks += 1
            dj = extract_chunk_block_state(cj[coord])
            dr = extract_chunk_block_state(cr[coord])
            if dj is None or dr is None:
                continue
            
            sec_j = dj["sections"]
            sec_r = dr["sections"]
            all_sy = sorted(set(sec_j.keys()).union(sec_r.keys()))
            
            chunk_exact = True
            chunk_blocks_only = True
            
            for sy in all_sy:
                if sy not in sec_j or sy not in sec_r:
                    chunk_exact = False
                    chunk_blocks_only = False
                    continue
                
                bj = sec_j[sy]["Blocks"]
                br = sec_r[sy]["Blocks"]
                data_j = sec_j[sy]["Data"]
                data_r = sec_r[sy]["Data"]
                
                is_base = (sy < 4) # below y=64 (underground/sea level)
                if is_base:
                    base_terrain_sections_compared += 1
                else:
                    surface_sections_compared += 1
                
                sec_blocks_match = (bj == br)
                sec_data_match = (data_j == data_r)
                
                if sec_blocks_match:
                    if is_base:
                        base_terrain_sections_identical += 1
                    else:
                        surface_sections_identical += 1
                else:
                    chunk_blocks_only = False
                    for bidx in range(len(bj)):
                        if bj[bidx] != br[bidx]:
                            mismatched_blocks_total += 1
                            mismatched_block_ids[(bj[bidx], br[bidx])] += 1
                            if is_base:
                                base_terrain_blocks_mismatched += 1
                
                if not sec_blocks_match or not sec_data_match:
                    chunk_exact = False
            
            if chunk_exact:
                identical_chunks_exact += 1
            if chunk_blocks_only:
                identical_chunks_blocks += 1
                
    print("==================================================================")
    print("TWIN-WORLD COMPREHENSIVE TERRAIN PARITY ANALYSIS")
    print("==================================================================")
    print(f"Total Chunks Compared:               {total_chunks}")
    print(f"100% Exact Bitwise Identical Chunks: {identical_chunks_exact} ({identical_chunks_exact/total_chunks*100:.2f}%)")
    print(f"Block-ID Identical Chunks:           {identical_chunks_blocks} ({identical_chunks_blocks/total_chunks*100:.2f}%)")
    print("")
    print(f"Base Terrain Sections (Y < 4):")
    print(f"  Sections Compared:  {base_terrain_sections_compared}")
    print(f"  Sections Identical: {base_terrain_sections_identical} ({base_terrain_sections_identical/base_terrain_sections_compared*100:.4f}%)")
    print(f"  Blocks Mismatched:  {base_terrain_blocks_mismatched}")
    print("")
    print(f"Surface/Air Sections (Y >= 4):")
    print(f"  Sections Compared:  {surface_sections_compared}")
    print(f"  Sections Identical: {surface_sections_identical} ({surface_sections_identical/surface_sections_compared*100:.4f}%)")
    print("")
    print("Top 15 Mismatched (Block_J, Block_R) pairs across entire world:")
    for (bid_j, bid_r), count in mismatched_block_ids.most_common(15):
        print(f"  J_id={bid_j:3d} vs R_id={bid_r:3d} : count={count}")

if __name__ == "__main__":
    analyze_all_chunks("machine/targetA/world-worldj", "machine/targetA/world-worldr")
