package com.rustcraft.coremod;

/**
 * GENERATED by tools/live-capture/generate_live_writer_plan.py from the committed
 * pre-hook profile tools/live-capture/live-shadow-profile.json
 * (manifest tools/live-capture/required-live-writer-hooks.json @ 738f672dd699ffb1…).
 * Do not edit by hand. V2 entries are observed recipe inputs, not certificates.
 * Historical entries retain their original diagnostic classification. The
 * transformers refuse to instrument anything that is not in this plan, and each
 * entry carries the pre-hook class hash that the source bytes must match.
 *
 * Profile identity bound at generation: minecraft_server fe1f9274e6dad919…,
 * forge build 14.23.5.2860, profile FORGE_2860_SERVER_TRANSFORMED_FML_INITIALIZED_OFFLINE_V1.
 */
public final class LiveWriterPlan {
    public static final String[][] EMPTY_FINGERPRINT = new String[0][];

    public static final class Hook {
        public final String id;
        public final String transformer;   // OWNERSHIP | PUBLICATION | PACKET
        public final String className;     // fully-qualified transformed name
        public final String methodName;    // SRG/runtime name; <init> for constructors
        public final String descriptor;    // exact JVM descriptor
        public final String hookType;      // WRITE_BEGIN | PRIVATE_BUILD_BEGIN | ...
        public final String operationId;   // unique injected marker + duplicate-detection anchor
        public final String[][] fingerprint; // {bci, expected instruction fragment} or empty
        public final String preHookClassSha256;
        public final boolean canonicalIdentity;
        public final String identitySchema;
        public final String declarationOrderSha256;
        /** Session-bound identity mode requires this certificate; null for every other mode. */
        public final String sessionCertificateJson;
        public final String sessionInvariantSha256;

        Hook(String id, String transformer, String className, String methodName, String descriptor,
             String hookType, String operationId, String[][] fingerprint, String preHookClassSha256,
             boolean canonicalIdentity) {
            this(id, transformer, className, methodName, descriptor, hookType, operationId,
                    fingerprint, preHookClassSha256,
                    canonicalIdentity ? "CANONICAL_ID_V1" : "RAW", null, null, null);
        }

        Hook(String id, String transformer, String className, String methodName, String descriptor,
             String hookType, String operationId, String[][] fingerprint, String preHookClassSha256,
             String identitySchema, String declarationOrderSha256) {
            this(id, transformer, className, methodName, descriptor, hookType, operationId,
                    fingerprint, preHookClassSha256, identitySchema, declarationOrderSha256, null, null);
        }

        Hook(String id, String transformer, String className, String methodName, String descriptor,
             String hookType, String operationId, String[][] fingerprint, String preHookClassSha256,
             String identitySchema, String declarationOrderSha256, String sessionCertificateJson,
             String sessionInvariantSha256) {
            this.id = id;
            this.transformer = transformer;
            this.className = className;
            this.methodName = methodName;
            this.descriptor = descriptor;
            this.hookType = hookType;
            this.operationId = operationId;
            this.fingerprint = fingerprint;
            this.preHookClassSha256 = preHookClassSha256;
            this.canonicalIdentity = "CANONICAL_ID_V1".equals(identitySchema);
            this.identitySchema = identitySchema;
            this.declarationOrderSha256 = declarationOrderSha256;
            this.sessionCertificateJson = sessionCertificateJson;
            this.sessionInvariantSha256 = sessionInvariantSha256;
        }

        public boolean sessionBound() {
            return "CANONICAL_ID_V2_SESSION_BOUND".equals(identitySchema);
        }

        public boolean hasFingerprint() {
            return fingerprint != EMPTY_FINGERPRINT && fingerprint.length > 0;
        }
    }

    /** Negative-control factory: same hook with a wrong pre-hook class hash. */
    public static Hook doctoredSha(Hook hook, String sha) {
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, hook.descriptor,
                hook.hookType, hook.operationId, hook.fingerprint, sha, hook.identitySchema,
                hook.declarationOrderSha256, hook.sessionCertificateJson, hook.sessionInvariantSha256);
    }

    /** Negative-control factory: same hook with an altered descriptor. */
    public static Hook doctoredDescriptor(Hook hook, String descriptor) {
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, descriptor,
                hook.hookType, hook.operationId, hook.fingerprint, hook.preHookClassSha256, hook.identitySchema,
                hook.declarationOrderSha256, hook.sessionCertificateJson, hook.sessionInvariantSha256);
    }

    /** Negative-control factory: same hook with shifted/missing/duplicated anchors. */
    public static Hook doctoredFingerprint(Hook hook, String[][] fingerprint) {
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, hook.descriptor,
                hook.hookType, hook.operationId, fingerprint, hook.preHookClassSha256, hook.identitySchema,
                hook.declarationOrderSha256, hook.sessionCertificateJson, hook.sessionInvariantSha256);
    }

    /** Negative-control factory: same hook with a doctored session certificate. */
    public static Hook doctoredCertificate(Hook hook, String sessionCertificateJson) {
        return new Hook(hook.id, hook.transformer, hook.className, hook.methodName, hook.descriptor,
                hook.hookType, hook.operationId, hook.fingerprint, hook.preHookClassSha256, hook.identitySchema,
                hook.declarationOrderSha256, sessionCertificateJson, hook.sessionInvariantSha256);
    }

    /** Profile identity binding: any change here requires regeneration + requalification. */
    public static final String FORGE_BUILD = "14.23.5.2860";
    public static final String QUALIFICATION_PROFILE = "FORGE_2860_SERVER_TRANSFORMED_FML_INITIALIZED_OFFLINE_V1";
    public static final String REQUIRED_HOOKS_MANIFEST_SHA256 = "738f672dd699ffb1474a4e82047577d73949c7a7e9a67838450852b06782cd32";
    public static final String IDENTITY_MODE = "RAW";

    public static final Hook[] HOOKS = {
        new Hook("W01", "OWNERSHIP", "net.minecraft.world.World", "func_180501_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;I)Z", "WRITE_BEGIN", "liveWriter.W01.World.func_180501_a", EMPTY_FINGERPRINT, "5deb85ca3424a85c32b132c763e774a419e32676c8d520ef2677fa7bc695858a", "RAW", null, null, null),
        new Hook("W02", "OWNERSHIP", "net.minecraft.world.World", "func_175653_a", "(Lnet/minecraft/world/EnumSkyBlock;Lnet/minecraft/util/math/BlockPos;I)V", "WRITE_BEGIN", "liveWriter.W02.World.func_175653_a", EMPTY_FINGERPRINT, "5deb85ca3424a85c32b132c763e774a419e32676c8d520ef2677fa7bc695858a", "RAW", null, null, null),
        new Hook("W03", "OWNERSHIP", "net.minecraft.world.World", "func_175690_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/tileentity/TileEntity;)V", "WRITE_BEGIN", "liveWriter.W03.World.func_175690_a", EMPTY_FINGERPRINT, "5deb85ca3424a85c32b132c763e774a419e32676c8d520ef2677fa7bc695858a", "RAW", null, null, null),
        new Hook("W04", "OWNERSHIP", "net.minecraft.world.World", "func_175713_t", "(Lnet/minecraft/util/math/BlockPos;)V", "WRITE_BEGIN", "liveWriter.W04.World.func_175713_t", EMPTY_FINGERPRINT, "5deb85ca3424a85c32b132c763e774a419e32676c8d520ef2677fa7bc695858a", "RAW", null, null, null),
        new Hook("W05", "OWNERSHIP", "net.minecraft.world.World", "func_180500_c", "(Lnet/minecraft/world/EnumSkyBlock;Lnet/minecraft/util/math/BlockPos;)Z", "WRITE_BEGIN", "liveWriter.W05.World.func_180500_c", EMPTY_FINGERPRINT, "5deb85ca3424a85c32b132c763e774a419e32676c8d520ef2677fa7bc695858a", "RAW", null, null, null),
        new Hook("W06", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76603_b", "()V", "WRITE_BEGIN", "liveWriter.W06.Chunk.func_76603_b", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W07", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76595_e", "(II)V", "WRITE_BEGIN", "liveWriter.W07.Chunk.func_76595_e", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W08", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_150803_c", "(Z)V", "WRITE_BEGIN", "liveWriter.W08.Chunk.func_150803_c", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W09", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76599_g", "(III)V", "WRITE_BEGIN", "liveWriter.W09.Chunk.func_76599_g", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W10", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76609_d", "(IIII)V", "WRITE_BEGIN", "liveWriter.W10.Chunk.func_76609_d", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W11", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76615_h", "(III)V", "WRITE_BEGIN", "liveWriter.W11.Chunk.func_76615_h", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W12", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177436_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)Lnet/minecraft/block/state/IBlockState;", "WRITE_BEGIN", "liveWriter.W12.Chunk.func_177436_a", new String[][]{{"203", "invokevirtual net/minecraft/world/chunk/storage/ExtendedBlockStorage.func_177484_a"}}, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W13", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177431_a", "(Lnet/minecraft/world/EnumSkyBlock;Lnet/minecraft/util/math/BlockPos;I)V", "WRITE_BEGIN", "liveWriter.W13.Chunk.func_177431_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W14", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177424_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/world/chunk/Chunk$EnumCreateEntityType;)Lnet/minecraft/tileentity/TileEntity;", "WRITE_BEGIN", "liveWriter.W14.Chunk.func_177424_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W15", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_150813_a", "(Lnet/minecraft/tileentity/TileEntity;)V", "WRITE_BEGIN", "liveWriter.W15.Chunk.func_150813_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W16", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177426_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/tileentity/TileEntity;)V", "WRITE_BEGIN", "liveWriter.W16.Chunk.func_177426_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W17", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177425_e", "(Lnet/minecraft/util/math/BlockPos;)V", "WRITE_BEGIN", "liveWriter.W17.Chunk.func_177425_e", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W18", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76631_c", "()V", "WRITE_BEGIN", "liveWriter.W18.Chunk.func_76631_c", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W19", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76623_d", "()V", "WRITE_BEGIN", "liveWriter.W19.Chunk.func_76623_d", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W20", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_186030_a", "(Lnet/minecraft/world/chunk/IChunkProvider;Lnet/minecraft/world/gen/IChunkGenerator;)V", "WRITE_BEGIN", "liveWriter.W20.Chunk.func_186030_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W21", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_186034_a", "(Lnet/minecraft/world/gen/IChunkGenerator;)V", "WRITE_BEGIN", "liveWriter.W21.Chunk.func_186034_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W22", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_150804_b", "(Z)V", "WRITE_BEGIN", "liveWriter.W22.Chunk.func_150804_b", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W23", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76602_a", "([Lnet/minecraft/world/chunk/storage/ExtendedBlockStorage;)V", "WRITE_BEGIN", "liveWriter.W23.Chunk.func_76602_a", new String[][]{{"49", "invokestatic java/lang/System.arraycopy"}}, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W24", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177411_a", "(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/world/biome/BiomeProvider;)Lnet/minecraft/world/biome/Biome;", "WRITE_BEGIN", "liveWriter.W24.Chunk.func_177411_a", new String[][]{{"92", "bastore"}}, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W25", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76616_a", "([B)V", "WRITE_BEGIN", "liveWriter.W25.Chunk.func_76616_a", new String[][]{{"49", "invokestatic java/lang/System.arraycopy"}}, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W26", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_76594_o", "()V", "WRITE_BEGIN", "liveWriter.W26.Chunk.func_76594_o", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W27", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_150809_p", "()V", "WRITE_BEGIN", "liveWriter.W27.Chunk.func_150809_p", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W28", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177441_y", "()V", "WRITE_BEGIN", "liveWriter.W28.Chunk.func_177441_y", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W29", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_180700_a", "(Lnet/minecraft/util/EnumFacing;)V", "WRITE_BEGIN", "liveWriter.W29.Chunk.func_180700_a", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W30", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_150811_f", "(II)Z", "WRITE_BEGIN", "liveWriter.W30.Chunk.func_150811_f", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W31", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177446_d", "(Z)V", "WRITE_BEGIN", "liveWriter.W31.Chunk.func_177446_d", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W32", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "func_177421_e", "(Z)V", "WRITE_BEGIN", "liveWriter.W32.Chunk.func_177421_e", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W33", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "removeInvalidTileEntity", "(Lnet/minecraft/util/math/BlockPos;)V", "WRITE_BEGIN", "liveWriter.W33.Chunk.removeInvalidTileEntity", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W34", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "<init>", "(Lnet/minecraft/world/World;II)V", "PRIVATE_BUILD_BEGIN", "liveWriter.W34.Chunk.ctor", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W35", "OWNERSHIP", "net.minecraft.world.chunk.Chunk", "<init>", "(Lnet/minecraft/world/World;Lnet/minecraft/world/chunk/ChunkPrimer;II)V", "PRIVATE_BUILD_BEGIN", "liveWriter.W35.Chunk.ctor", EMPTY_FINGERPRINT, "0bd20899a444608e1f49f93a2a0a0b594a5cedb81d7202adfc54fd4e3417e7e3", "RAW", null, null, null),
        new Hook("W36", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "<init>", "(IZ)V", "PRIVATE_BUILD_BEGIN", "liveWriter.W36.ExtendedBlockStorage.ctor", EMPTY_FINGERPRINT, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W37", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "func_177484_a", "(IIILnet/minecraft/block/state/IBlockState;)V", "WRITE_BEGIN", "liveWriter.W37.ExtendedBlockStorage.func_177484_a", new String[][]{{"62", "putfield field_76682_b:I"}, {"116", "putfield field_76683_c:I"}}, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W38", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "func_76657_c", "(IIII)V", "WRITE_BEGIN", "liveWriter.W38.ExtendedBlockStorage.func_76657_c", EMPTY_FINGERPRINT, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W39", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "func_76677_d", "(IIII)V", "WRITE_BEGIN", "liveWriter.W39.ExtendedBlockStorage.func_76677_d", EMPTY_FINGERPRINT, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W40", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "func_76672_e", "()V", "WRITE_BEGIN", "liveWriter.W40.ExtendedBlockStorage.func_76672_e", EMPTY_FINGERPRINT, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W41", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "func_76659_c", "(Lnet/minecraft/world/chunk/NibbleArray;)V", "WRITE_BEGIN", "liveWriter.W41.ExtendedBlockStorage.func_76659_c", EMPTY_FINGERPRINT, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W42", "OWNERSHIP", "net.minecraft.world.chunk.storage.ExtendedBlockStorage", "func_76666_d", "(Lnet/minecraft/world/chunk/NibbleArray;)V", "WRITE_BEGIN", "liveWriter.W42.ExtendedBlockStorage.func_76666_d", EMPTY_FINGERPRINT, "b7445c7bd232e8debf2c6ed47438b890d6bd121e406455cdc3cb9e84b487cd23", "RAW", null, null, null),
        new Hook("W43", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "<init>", "()V", "PRIVATE_BUILD_BEGIN", "liveWriter.W43.BlockStateContainer.ctor", EMPTY_FINGERPRINT, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W44", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "func_186012_b", "(I)V", "WRITE_BEGIN", "liveWriter.W44.BlockStateContainer.func_186012_b", EMPTY_FINGERPRINT, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W45", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "setBits", "(IZ)V", "WRITE_BEGIN", "liveWriter.W45.BlockStateContainer.setBits", new String[][]{{"99", "putfield field_186024_e:I"}}, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W46", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "func_186008_a", "(ILnet/minecraft/block/state/IBlockState;)I", "WRITE_BEGIN", "liveWriter.W46.BlockStateContainer.func_186008_a", EMPTY_FINGERPRINT, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W47", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "func_186013_a", "(IIILnet/minecraft/block/state/IBlockState;)V", "WRITE_BEGIN", "liveWriter.W47.BlockStateContainer.func_186013_a", EMPTY_FINGERPRINT, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W48", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "func_186014_b", "(ILnet/minecraft/block/state/IBlockState;)V", "WRITE_BEGIN", "liveWriter.W48.BlockStateContainer.func_186014_b", EMPTY_FINGERPRINT, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W49", "OWNERSHIP", "net.minecraft.world.chunk.BlockStateContainer", "func_186019_a", "([BLnet/minecraft/world/chunk/NibbleArray;Lnet/minecraft/world/chunk/NibbleArray;)V", "WRITE_BEGIN", "liveWriter.W49.BlockStateContainer.func_186019_a", EMPTY_FINGERPRINT, "9720a0dede53bd654fc6704b4251499f1bf1d853b56cd52f75b465b7956716bc", "RAW", null, null, null),
        new Hook("W50", "OWNERSHIP", "net.minecraft.world.chunk.NibbleArray", "<init>", "()V", "PRIVATE_BUILD_BEGIN", "liveWriter.W50.NibbleArray.ctor", EMPTY_FINGERPRINT, "b5556356777ea7c17ecfd1ceec588da0aa8e183ee5305a16438215eaf297285f", "RAW", null, null, null),
        new Hook("W51", "OWNERSHIP", "net.minecraft.world.chunk.NibbleArray", "<init>", "([B)V", "PRIVATE_BUILD_BEGIN", "liveWriter.W51.NibbleArray.ctor", EMPTY_FINGERPRINT, "b5556356777ea7c17ecfd1ceec588da0aa8e183ee5305a16438215eaf297285f", "RAW", null, null, null),
        new Hook("W52", "OWNERSHIP", "net.minecraft.world.chunk.NibbleArray", "func_76581_a", "(IIII)V", "WRITE_BEGIN", "liveWriter.W52.NibbleArray.func_76581_a", EMPTY_FINGERPRINT, "b5556356777ea7c17ecfd1ceec588da0aa8e183ee5305a16438215eaf297285f", "RAW", null, null, null),
        new Hook("W53", "OWNERSHIP", "net.minecraft.world.chunk.NibbleArray", "func_177482_a", "(II)V", "WRITE_BEGIN", "liveWriter.W53.NibbleArray.func_177482_a", EMPTY_FINGERPRINT, "b5556356777ea7c17ecfd1ceec588da0aa8e183ee5305a16438215eaf297285f", "RAW", null, null, null),
        new Hook("W54", "OWNERSHIP", "net.minecraft.util.BitArray", "func_188141_a", "(II)V", "WRITE_BEGIN", "liveWriter.W54.BitArray.func_188141_a", EMPTY_FINGERPRINT, "d967a3fc91e099fd8d1ad4b3655cf90950ebb43f181344e1b4d5a5a3fb69be35", "RAW", null, null, null),
        new Hook("W55", "OWNERSHIP", "net.minecraft.util.BitArray", "<init>", "(II)V", "PRIVATE_BUILD_BEGIN", "liveWriter.W55.BitArray.ctor", EMPTY_FINGERPRINT, "d967a3fc91e099fd8d1ad4b3655cf90950ebb43f181344e1b4d5a5a3fb69be35", "RAW", null, null, null),
        new Hook("W56", "PUBLICATION", "net.minecraft.world.gen.ChunkProviderServer", "loadChunk", "(IILjava/lang/Runnable;)Lnet/minecraft/world/chunk/Chunk;", "WRITE_BEGIN", "liveWriter.W56.ChunkProviderServer.loadChunk", new String[][]{{"131", "invokeinterface it/unimi/dsi/fastutil/longs/Long2ObjectMap.put"}}, "6eec9a968581e993495d79b9410e37d3e6b70da5b7de08ae72b3475311f63914", "RAW", null, null, null),
        new Hook("W57", "PUBLICATION", "net.minecraft.world.gen.ChunkProviderServer", "func_186025_d", "(II)Lnet/minecraft/world/chunk/Chunk;", "WRITE_BEGIN", "liveWriter.W57.ChunkProviderServer.func_186025_d", new String[][]{{"125", "invokeinterface it/unimi/dsi/fastutil/longs/Long2ObjectMap.put"}}, "6eec9a968581e993495d79b9410e37d3e6b70da5b7de08ae72b3475311f63914", "RAW", null, null, null),
        new Hook("W58", "PUBLICATION", "net.minecraft.world.gen.ChunkProviderServer", "func_73156_b", "()Z", "LIFECYCLE_RETIRE", "liveWriter.W58.ChunkProviderServer.func_73156_b", new String[][]{{"149", "invokevirtual net/minecraft/world/chunk/Chunk.func_76623_d"}, {"167", "invokestatic net/minecraftforge/common/ForgeChunkManager.putDormantChunk"}, {"173", "invokespecial func_73242_b"}, {"179", "invokespecial func_73243_a"}, {"187", "invokeinterface it/unimi/dsi/fastutil/longs/Long2ObjectMap.remove"}}, "6eec9a968581e993495d79b9410e37d3e6b70da5b7de08ae72b3475311f63914", "RAW", null, null, null),
        new Hook("W59", "PUBLICATION", "net.minecraftforge.common.chunkio.ChunkIOProvider", "run", "()V", "PRIVATE_BUILD_END", "liveWriter.W59.ChunkIOProvider.run", new String[][]{{"59", "putfield nbt:Lnet/minecraft/nbt/NBTTagCompound;"}, {"69", "putfield chunk:Lnet/minecraft/world/chunk/Chunk;"}, {"74", "putfield ran:Z"}, {"88", "putfield ran:Z"}}, "e2c76022ef993b0079f62b6a0671a17fd4bf232fa5bf83e01cb66196e6af50d1", "RAW", null, null, null),
        new Hook("W60", "PUBLICATION", "net.minecraftforge.common.chunkio.ChunkIOProvider", "syncCallback", "()V", "PUBLICATION_BEGIN", "liveWriter.W60.ChunkIOProvider.syncCallback", new String[][]{{"1", "getfield chunk:Lnet/minecraft/world/chunk/Chunk;"}, {"136", "invokeinterface it/unimi/dsi/fastutil/longs/Long2ObjectMap.put"}, {"146", "invokevirtual net/minecraft/world/chunk/Chunk.func_76631_c"}, {"164", "invokevirtual net/minecraft/world/chunk/Chunk.func_186030_a"}, {"168", "invokevirtual runCallbacks"}, {"171", "return"}}, "e2c76022ef993b0079f62b6a0671a17fd4bf232fa5bf83e01cb66196e6af50d1", "RAW", null, null, null),
        new Hook("S01", "PUBLICATION", "net.minecraft.server.MinecraftServer", "run", "()V", "DIAGNOSTIC_ONLY", "liveWriter.S01.MinecraftServer.run", EMPTY_FINGERPRINT, "97fa984df647eec377a38fb96798f7f6e22fecbb6ca7519d1a952e3c981a4d5b", "RAW", null, null, null),
        new Hook("S02", "PACKET", "net.minecraft.network.play.server.SPacketChunkData", "<init>", "(Lnet/minecraft/world/chunk/Chunk;I)V", "PACKET_CAPTURE", "liveWriter.S02.SPacketChunkData.ctor", new String[][]{{"1", "invokespecial java/lang/Object.\"<init>\""}, {"4", "aload_0"}, {"75", "invokevirtual func_189555_a"}, {"78", "putfield field_186948_c:I"}, {"180", "invokevirtual net/minecraft/tileentity/TileEntity.func_189517_E_"}, {"200", "return"}}, "9e8abff74ea6266a4793bfa03bbff9731d2c486c9ff34e5a67b81752ec063354", "RAW", null, null, null),
        new Hook("S03", "PUBLICATION", "net.minecraft.world.chunk.storage.AnvilChunkLoader", "loadChunk__Async", "(Lnet/minecraft/world/World;II)[Ljava/lang/Object;", "PRIVATE_BUILD_BEGIN", "liveWriter.S03.AnvilChunkLoader.loadChunk__Async", new String[][]{{"17", "invokeinterface java/util/Map.get"}, {"29", "ifnonnull"}, {"59", "invokestatic net/minecraft/nbt/CompressedStreamTools.func_74794_a"}, {"62", "invokevirtual net/minecraft/util/datafix/DataFixer.func_188257_a"}, {"69", "invokevirtual java/io/DataInputStream.close"}, {"78", "invokevirtual checkedReadChunkFromNBT__Async"}}, "24fff9a48dec4d82d08caab7484b8b53587ff2110703763675707369dcd91595", "RAW", null, null, null),
        new Hook("S04", "PUBLICATION", "net.minecraft.world.chunk.storage.AnvilChunkLoader", "checkedReadChunkFromNBT__Async", "(Lnet/minecraft/world/World;IILnet/minecraft/nbt/NBTTagCompound;)[Ljava/lang/Object;", "PRIVATE_BUILD_BEGIN", "liveWriter.S04.AnvilChunkLoader.checkedReadChunkFromNBT__Async", EMPTY_FINGERPRINT, "24fff9a48dec4d82d08caab7484b8b53587ff2110703763675707369dcd91595", "RAW", null, null, null),
        new Hook("S05", "PUBLICATION", "net.minecraft.world.chunk.storage.AnvilChunkLoader", "func_75823_a", "(Lnet/minecraft/world/World;Lnet/minecraft/nbt/NBTTagCompound;)Lnet/minecraft/world/chunk/Chunk;", "PRIVATE_BUILD_BEGIN", "liveWriter.S05.AnvilChunkLoader.func_75823_a", EMPTY_FINGERPRINT, "24fff9a48dec4d82d08caab7484b8b53587ff2110703763675707369dcd91595", "RAW", null, null, null),
        new Hook("S06", "PUBLICATION", "net.minecraft.world.gen.ChunkGeneratorFlat", "func_185932_a", "(II)Lnet/minecraft/world/chunk/Chunk;", "DIAGNOSTIC_ONLY", "liveWriter.S06.ChunkGeneratorFlat.func_185932_a", new String[][]{{"184", "invokevirtual net/minecraft/world/chunk/Chunk.func_76605_m"}, {"213", "bastore"}, {"222", "invokevirtual net/minecraft/world/chunk/Chunk.func_76603_b"}}, "d8bcb37048eb58380e2b162981ca7c35bfcbccf334e3241e4902166fcb010db9", "RAW", null, null, null)
    };

    private LiveWriterPlan() { }
}
